package box_sorter;
//-----------------------------------------------------------------------------
/**
 * @author judsonjames
 * @since 03-15-2017
 * @version 1.0
 * <h1><b>Lab 17 -- Box Object</b></h1>
 * <p>
 * This class is designed to be used as a wrapper-class of a box that contains
 * 'double' values for the length, width, and height of the box, and a 'String'
 * that is used as a name for the box. The boxes also contain a volume, and as
 * such the boxes will be sorted by volume in the BoxSorter class.
 * </p>
 * <p>
 * The methods used within this class are primarily getters and setters,
 * however, there are also a getVolume method which returns the volume of the
 * box, and a toString method.
 * </p>
 */
//-----------------------------------------------------------------------------

public class Box {

  private String label;
  private double length;
  private double width;
  private double height;
  
  //---------------------------------------------------------------------------
  // Constructors for Box
  //---------------------------------------------------------------------------
  public Box () {
    setLabel("no label yet");
    setLength(1.0);
    setWidth(1.0);
    setHeight(1.0);
  }
  
  public Box (String aLabel, double aLength,
              double aWidth, double aHeight) {
    setLabel(aLabel);
    setLength(aLength);
    setWidth(aWidth);
    setHeight(aHeight);
  }
  //---------------------------------------------------------------------------
  // Getters and Setters Generated by Eclipse
  //---------------------------------------------------------------------------
  public String getLabel() {
    return label;
  }
  
  public void setLabel(String label) {
    this.label = label;
  }
  
  public double getLength() {
    return length;
  }
  
  public void setLength(double length) {
    if (length > 0.0) {
      this.length = length;
    }
    else {
      this.length = 1.0;
    }
  }
  
  public double getWidth() {
    return width;
  }
  
  public void setWidth(double width) {
    if (width > 0.0) {
      this.width = width;
    }
    else {
      this.width = 1.0;
    }
  }
  
  public double getHeight() {
    return height;
  }
  public void setHeight(double height) {
    if (height > 0.0) {
      this.height = height;
    }
    else {
      this.height = 1.0;
    }
  }
  
  //---------------------------------------------------------------------------
  // Other Methods
  //---------------------------------------------------------------------------
  
  // public double getVolume() -- Returns the volume of the box (l*w*h)
  public double getVolume() {
    return (this.length * this.width * this.height);
  }

  // toString generated by Eclipse
  @Override
  public String toString() {
    return "Box [label=" + label + ", length=" + length 
        + ", width=" + width + ", height=" + height + "]";
  }
} // end of Box
